# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import recommonmark
from recommonmark.transform import AutoStructify
from recommonmark.parser import CommonMarkParser

sys.path.insert(0, os.path.abspath("."))


# -- Project information -----------------------------------------------------

project = "RF24 Revemped"
copyright = "2020, 2bndy5"
author = "2bndy5"

# The full version, including alpha/beta/rc tags
release = "2.0"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "breathe",
    "recommonmark",
    "sphinx.ext.autosectionlabel",
    # "sphinx.ext.intersphinx",
]

# intersphinx_mapping = {"python": ("https://docs.python.org/3.7", None)}


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

source_suffix = {
    ".rst": "restructuredtext",
    ".txt": "markdown",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".env", "CODE_OF_CONDUCT.md"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
#
# default_role = "any"

# if this is set true, it appends parenthesis to function
# signatures causing cross-reference errors in sphinx's cpp
# domain. maybe also caused from using breathe?
# add_function_parentheses = True

# Tell sphinx what the primary language being documented is.
primary_domain = "cpp"

# Tell sphinx what the pygments highlight language should be.
highlight_language = "cpp"

# breathe configuration
# ---------------------------------------------

# autodoxygen directives are not as useful as you think
# breathe_projects_source = {
#     "RF24":
#     ("../", ["RF24.h", "RF24.cpp", "RF24_config.h", "nRF24L01.h"])
# }

breathe_projects = {"RF24": "./doxygen/xml"}
breathe_default_project = "RF24"

# recommonmark Configuration
# -------------------------------------------------


def visit_document(*_):
    pass


# Removes irrelevant warning messages during md file parsing.
# REF: https://github.com/readthedocs/recommonmark/issues/177
# Hopefully will be unnecessary in the future (when recommonmark > 0.6.0 exists)
setattr(CommonMarkParser, "visit_document", visit_document)

# app setup hook
def setup(app):
    app.add_config_value(
        "recommonmark_config",
        {
            #'url_resolver': lambda url: github_doc_root + url,
            # 'auto_toc_tree_section': 'Contents',
            # 'enable_math': False,
            # 'enable_inline_math': False,
            "enable_eval_rst": True,
        },
        True,
    )
    app.add_transform(AutoStructify)


# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
# autosectionlabel_prefix_document = True

# Options for HTML output
# -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    "darkness.css",
]

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
html_favicon = "_static/favicon.ico"

html_logo = "_static/Logo.png"

# Output file base name for HTML help builder.
htmlhelp_basename = "RF24RevampedLibrarydoc"