name: Linux build

on:
  pull_request:
    branches: [master]
    paths:
      - "*.h"
      - "*.cpp"
      - "CMakeLists.txt"
      - "cmake/**"
      - "library.properties" # CMake & 'configure' gets lib info from here
      - "utility/CMakeLists.txt"
      # - "utility/LittleWire/*"" # this is not tested (anymore)
      - "utility/SPIDEV/*"
      - "examples/linux/**"
      - "!examples/linux/*.py"
      - "!examples/linux/*.md"
      - "pyRF24/setup.py"
      - "pyRF24/pyRF24.cpp"
      - ".github/workflows/build_linux.yml"
  push:
    branches: [master]
    paths:
      - "*.h"
      - "*.cpp"
      - "CMakeLists.txt"
      - "cmake/**"
      - "library.properties" # CMake & 'configure' gets lib info from here
      - "utility/CMakeLists.txt"
      # - "utility/LittleWire/*"" # this is not tested (anymore)
      - "utility/SPIDEV/*"
      - "examples/linux/**"
      - "!examples/linux/*.py"
      - "!examples/linux/*.md"
      - "pyRF24/setup.py"
      - "pyRF24/pyRF24.cpp"
      - ".github/workflows/build_linux.yml"
  release:
    types: [created]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ####################### using CMake ################################
  build:
    uses: nRF24/.github/.github/workflows/build_linux_cmake.yaml@main
    with:
      rf24-ref: ${{ github.sha }}
      driver: ${{ matrix.driver }}
      compiler: ${{ matrix.toolchain.compiler }}
      usr-dir: ${{ matrix.toolchain.usr_dir }}
      examples-path: examples/linux
      deploy-release: ${{ github.event_name == 'release' && (matrix.toolchain.compiler == 'armhf' || matrix.toolchain.compiler == 'arm64') && (matrix.driver =='RPi' || matrix.driver =='SPIDEV') }}
      py-wrapper-path: pyRF24
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - compiler: "armhf"
            usr_dir: "arm-linux-gnueabihf"
          - compiler: "arm64"
            usr_dir: "aarch64-linux-gnu"
          # - compiler: "x86_64"
          #   usr_dir: "x86_64-linux-gnux32"
          # - compiler: "i686"
          #   usr_dir: "i686-linux-gnu"
          - compiler: "default" # github runner is hosted on a "amd64"
            usr_dir: "local" # using this toolchain to test python wrapper
        driver:
          - "SPIDEV"
